# Generated by Django 5.2.5 on 2025-09-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'profile')},
        ),
    ]
