# Generated by Django 5.2.5 on 2025-09-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_alter_like_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Like",
            new_name="PostLike",
        ),
        migrations.AlterModelTable(
            name="postlike",
            table="social_postlike",
        ),
    ]
