# Generated by Django 5.2.5 on 2025-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_like_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
