# Generated by Django 5.2.5 on 2025-10-28 06:02

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='cover_photo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='profile_pics/default.jpg', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='profile_pics/'),
        ),
    ]
