# Generated by Django 5.2.5 on 2025-10-28 14:25

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='The optional image for the post.', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='The text content of the post.', null=True),
        ),
    ]
