# Generated by Django 5.2.5 on 2025-11-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
