# Generated by Django 5.2.5 on 2025-11-29 03:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_postimage_height_postimage_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='post_images'),
        ),
    ]
